/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author Aluno
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    double v1, v2, resultado;
    String operacao;
    public calculadora() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void formWindowActivated(java.awt.event.WindowEvent evt){
        //  TODO add your handling code here: 
        //  URL iconURL = getClass().getResource("calc.ico")
        
        //ImageIcon icon = new ImageIcon(iconURL);
        //this.setIconImage(icon.getImage());
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Visor = new javax.swing.JPanel();
        txtVisor = new javax.swing.JTextField();
        painelbotoes = new javax.swing.JPanel();
        btmc = new javax.swing.JButton();
        btmr = new javax.swing.JButton();
        btms = new javax.swing.JButton();
        btmmais = new javax.swing.JButton();
        btmmenos = new javax.swing.JButton();
        btapagar = new javax.swing.JButton();
        btce = new javax.swing.JButton();
        btc = new javax.swing.JButton();
        btmaismenos = new javax.swing.JButton();
        btraiz = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btdividir = new javax.swing.JButton();
        btporcentagem = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        btvezes = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btmenos = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btvirgula = new javax.swing.JButton();
        btmais = new javax.swing.JButton();
        btigual = new javax.swing.JButton();
        bt1sobrex = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem7 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("calculadora");

        Visor.setBackground(new java.awt.Color(51, 255, 255));
        Visor.setName(""); // NOI18N

        txtVisor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVisor.setText("0");
        txtVisor.setEnabled(false);
        txtVisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVisorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VisorLayout = new javax.swing.GroupLayout(Visor);
        Visor.setLayout(VisorLayout);
        VisorLayout.setHorizontalGroup(
            VisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVisor)
                .addContainerGap())
        );
        VisorLayout.setVerticalGroup(
            VisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VisorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVisor, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelbotoes.setBackground(new java.awt.Color(153, 153, 153));

        btmc.setText("MC");
        btmc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmcActionPerformed(evt);
            }
        });

        btmr.setText("MR");

        btms.setText("MS");

        btmmais.setText("M+");

        btmmenos.setText("M-");

        btapagar.setText("←");
        btapagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btapagarMouseClicked(evt);
            }
        });
        btapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btapagarActionPerformed(evt);
            }
        });

        btce.setText("CE");
        btce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btceMouseClicked(evt);
            }
        });

        btc.setText("C");
        btc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcMouseClicked(evt);
            }
        });

        btmaismenos.setText("+-");
        btmaismenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmaismenosMouseClicked(evt);
            }
        });

        btraiz.setText("√");
        btraiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btraizMouseClicked(evt);
            }
        });
        btraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btraizActionPerformed(evt);
            }
        });

        bt7.setText("7");
        bt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt7MouseClicked(evt);
            }
        });

        bt8.setText("8");
        bt8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt8MouseClicked(evt);
            }
        });

        bt9.setText("9");
        bt9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt9MouseClicked(evt);
            }
        });

        btdividir.setText("/");
        btdividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btdividirMouseClicked(evt);
            }
        });

        btporcentagem.setText("%");
        btporcentagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btporcentagemMouseClicked(evt);
            }
        });
        btporcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btporcentagemActionPerformed(evt);
            }
        });

        bt4.setText("4");
        bt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt4MouseClicked(evt);
            }
        });

        bt5.setText("5");
        bt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt5MouseClicked(evt);
            }
        });

        bt6.setText("6");
        bt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt6MouseClicked(evt);
            }
        });

        btvezes.setText("*");
        btvezes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvezesMouseClicked(evt);
            }
        });

        bt1.setText("1");
        bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt1MouseClicked(evt);
            }
        });

        bt2.setText("2");
        bt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt2MouseClicked(evt);
            }
        });

        bt3.setText("3");
        bt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt3MouseClicked(evt);
            }
        });
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        btmenos.setText("-");
        btmenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmenosMouseClicked(evt);
            }
        });

        bt0.setText("0");
        bt0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt0MouseClicked(evt);
            }
        });

        btvirgula.setText(",");
        btvirgula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvirgulaMouseClicked(evt);
            }
        });

        btmais.setText("+");
        btmais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmaisMouseClicked(evt);
            }
        });

        btigual.setText("=");
        btigual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btigualMouseClicked(evt);
            }
        });

        bt1sobrex.setText("1/x");
        bt1sobrex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt1sobrexMouseClicked(evt);
            }
        });
        bt1sobrex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1sobrexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelbotoesLayout = new javax.swing.GroupLayout(painelbotoes);
        painelbotoes.setLayout(painelbotoesLayout);
        painelbotoesLayout.setHorizontalGroup(
            painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelbotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelbotoesLayout.createSequentialGroup()
                        .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btapagar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btmc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btmr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(bt0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btvirgula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelbotoesLayout.createSequentialGroup()
                        .addComponent(btmmais, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btmmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, Short.MAX_VALUE))
                    .addGroup(painelbotoesLayout.createSequentialGroup()
                        .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btmenos, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btvezes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btmais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btigual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt1sobrex, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(painelbotoesLayout.createSequentialGroup()
                        .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btmaismenos, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btdividir, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btraiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btporcentagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        painelbotoesLayout.setVerticalGroup(
            painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelbotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmc)
                    .addComponent(btmr)
                    .addComponent(btms)
                    .addComponent(btmmais)
                    .addComponent(btmmenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btapagar)
                    .addComponent(btce)
                    .addComponent(btc)
                    .addComponent(btmaismenos)
                    .addComponent(btraiz, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt7)
                    .addComponent(bt8)
                    .addComponent(bt9)
                    .addComponent(btdividir)
                    .addComponent(btporcentagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt4)
                    .addComponent(bt5)
                    .addComponent(bt6)
                    .addComponent(btvezes)
                    .addComponent(bt1sobrex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelbotoesLayout.createSequentialGroup()
                        .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt1)
                            .addComponent(bt2)
                            .addComponent(bt3)
                            .addComponent(btmenos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt0)
                            .addComponent(btvirgula)
                            .addComponent(btmais)))
                    .addComponent(btigual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Exibir");

        jRadioButtonMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Padrão");
        jMenu1.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jRadioButtonMenuItem2.setSelected(false);
        jRadioButtonMenuItem2.setText("Científica");
        jMenu1.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jRadioButtonMenuItem3.setSelected(false);
        jRadioButtonMenuItem3.setText("Programador");
        jMenu1.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jRadioButtonMenuItem4.setSelected(false);
        jRadioButtonMenuItem4.setText("Estatística");
        jMenu1.add(jRadioButtonMenuItem4);
        jMenu1.add(jSeparator2);

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItem1.setSelected(false);
        jCheckBoxMenuItem1.setText("Histórico");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(false);
        jCheckBoxMenuItem2.setText("Agrupamento de dígitos");
        jMenu1.add(jCheckBoxMenuItem2);
        jMenu1.add(jSeparator3);

        jRadioButtonMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("Básico");
        jMenu1.add(jRadioButtonMenuItem5);

        jRadioButtonMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jRadioButtonMenuItem6.setSelected(false);
        jRadioButtonMenuItem6.setText("Conversão de unidades");
        jMenu1.add(jRadioButtonMenuItem6);

        jRadioButtonMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jRadioButtonMenuItem7.setSelected(false);
        jRadioButtonMenuItem7.setText("Cálculo de data");
        jMenu1.add(jRadioButtonMenuItem7);

        jMenu4.setText("Planilhas");
        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setText("Copiar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem7.setText("Colar");
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator1);

        jMenu5.setText("Histórico");
        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("Exibir Ajuda");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Sobre a Calculadora");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelbotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Visor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Visor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelbotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVisorActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btmcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmcActionPerformed

    private void btapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btapagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btapagarActionPerformed

    private void btraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btraizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btraizActionPerformed

    private void btporcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btporcentagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btporcentagemActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void bt1sobrexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1sobrexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt1sobrexActionPerformed

    private void bt7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt7MouseClicked
        // TODO add your handling code here:
        if(txtVisor.getText().equals("0"))
            txtVisor.setText("7");
        else
            txtVisor.setText(txtVisor.getText()+"7");
    }//GEN-LAST:event_bt7MouseClicked

    private void bt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseClicked
        // TODO add your handling code here:
        if(txtVisor.getText().equals("0"))
            txtVisor.setText("2");
        else
            txtVisor.setText(txtVisor.getText()+"2");
    }//GEN-LAST:event_bt2MouseClicked

    private void bt8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt8MouseClicked
        // TODO add your handling code here:
        if(txtVisor.getText().equals("0"))
            txtVisor.setText("8");
        else
            txtVisor.setText(txtVisor.getText()+"8");
    }//GEN-LAST:event_bt8MouseClicked

    private void bt9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt9MouseClicked
        // TODO add your handling code here:
        if(txtVisor.getText().equals("0"))
            txtVisor.setText("9");
        else
            txtVisor.setText(txtVisor.getText()+"9");
    }//GEN-LAST:event_bt9MouseClicked

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void bt6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt6MouseClicked
        // TODO add your handling code here:
        if(txtVisor.getText().equals("0"))
            txtVisor.setText("6");
        else
            txtVisor.setText(txtVisor.getText()+"6");
    }//GEN-LAST:event_bt6MouseClicked

    private void bt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt4MouseClicked
        // TODO add your handling code here:
        if(txtVisor.getText().equals("0"))
            txtVisor.setText("4");
        else
            txtVisor.setText(txtVisor.getText()+"4");
    }//GEN-LAST:event_bt4MouseClicked

    private void bt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseClicked
        // TODO add your handling code here:
        if(txtVisor.getText().equals("0"))
            txtVisor.setText("1");
        else
            txtVisor.setText(txtVisor.getText()+"1");
    }//GEN-LAST:event_bt1MouseClicked

    private void bt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt3MouseClicked
        // TODO add your handling code here:
        if(txtVisor.getText().equals("0"))
            txtVisor.setText("3");
        else
            txtVisor.setText(txtVisor.getText()+"3");
    }//GEN-LAST:event_bt3MouseClicked

    private void bt5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt5MouseClicked
        // TODO add your handling code here:
        if(txtVisor.getText().equals("0"))
            txtVisor.setText("5");
        else
            txtVisor.setText(txtVisor.getText()+"5");
    }//GEN-LAST:event_bt5MouseClicked

    private void bt0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt0MouseClicked
        // TODO add your handling code here:
        if(!txtVisor.getText().equals("0"))
            txtVisor.setText(txtVisor.getText()+"0");
    }//GEN-LAST:event_bt0MouseClicked

    private void btmaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmaisMouseClicked
        // TODO add your handling code here:
        v1 = Double.parseDouble(txtVisor.getText());
        txtVisor.setText("0");
        operacao = "soma";
    }//GEN-LAST:event_btmaisMouseClicked

    private void btigualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btigualMouseClicked
        // TODO add your handling code here:
        v2 = Double.parseDouble(txtVisor.getText());
        if(operacao.equals("soma"))
            resultado = v1+v2;
        else if(operacao.equals("subtracao"))
            resultado = v1-v2;
        else if(operacao.equals("multiplicacao"))
            resultado = v1*v2;
        else if(operacao.equals("divisao"))
            resultado = v1/v2;
        else if(operacao.equals("porcentagem"))
            resultado = ((v1/100)*v2);
        
        txtVisor.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btigualMouseClicked

    private void btmaismenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmaismenosMouseClicked
        // TODO add your handling code here:
        v1 = Double.parseDouble(txtVisor.getText());
        resultado = (v1*-1);
        txtVisor.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btmaismenosMouseClicked

    private void bt1sobrexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1sobrexMouseClicked
        // TODO add your handling code here:
        v1 = Double.parseDouble(txtVisor.getText());
        resultado = (1/v1);
        txtVisor.setText(String.valueOf(resultado));
    }//GEN-LAST:event_bt1sobrexMouseClicked

    private void btmenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmenosMouseClicked
        // TODO add your handling code here:
        v1 = Double.parseDouble(txtVisor.getText());
        txtVisor.setText("0");
        operacao = "subtracao";
    }//GEN-LAST:event_btmenosMouseClicked

    private void btvezesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvezesMouseClicked
        // TODO add your handling code here:
        v1 = Double.parseDouble(txtVisor.getText());
        txtVisor.setText("0");
        operacao = "multiplicacao";
    }//GEN-LAST:event_btvezesMouseClicked

    private void btdividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdividirMouseClicked
        // TODO add your handling code here:
        v1 = Double.parseDouble(txtVisor.getText());
        txtVisor.setText("0");
        operacao = "divisao";
    }//GEN-LAST:event_btdividirMouseClicked

    private void btraizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btraizMouseClicked
        // TODO add your handling code here:
        v1 = Double.parseDouble(txtVisor.getText());
        txtVisor.setText(String.valueOf(Math. sqrt(v1)));
    }//GEN-LAST:event_btraizMouseClicked

    private void btporcentagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btporcentagemMouseClicked
        // TODO add your handling code here:
       v1 = Double.parseDouble(txtVisor.getText());
       txtVisor.setText("0");
       operacao = "porcentagem";
    }//GEN-LAST:event_btporcentagemMouseClicked

    private void btapagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btapagarMouseClicked
        // TODO add your handling code here:
        
     //   v1 = Double.parseDouble(txtVisor.getText());
     //   v1 = (int)(v1/10);
        
     //   txtVisor.setText(String.valueOf(v1));
        
        String BackFieldText=txtVisor.getText();
        if (!"".equals(BackFieldText)){
            String SubStr = BackFieldText.substring(0,BackFieldText.length()-1);
            txtVisor.setText(""+SubStr);
        } 
    }//GEN-LAST:event_btapagarMouseClicked

    private void btcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcMouseClicked
        // TODO add your handling code here:
        v1 = 0;
        v2 = 0;
        resultado = 0;
        txtVisor.setText("0");
    }//GEN-LAST:event_btcMouseClicked

    private void btvirgulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvirgulaMouseClicked
        // TODO add your handling code here:
        txtVisor.setText(txtVisor.getText()+".");
    }//GEN-LAST:event_btvirgulaMouseClicked

    private void btceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btceMouseClicked
        // TODO add your handling code here:
        if(v1 != 0){
            v2 = 0;
        txtVisor.setText("0");
        }
        else if(v1 == 0){
            v1 = 0;
        txtVisor.setText("0");
        }
        
    }//GEN-LAST:event_btceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Visor;
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt1sobrex;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btapagar;
    private javax.swing.JButton btc;
    private javax.swing.JButton btce;
    private javax.swing.JButton btdividir;
    private javax.swing.JButton btigual;
    private javax.swing.JButton btmais;
    private javax.swing.JButton btmaismenos;
    private javax.swing.JButton btmc;
    private javax.swing.JButton btmenos;
    private javax.swing.JButton btmmais;
    private javax.swing.JButton btmmenos;
    private javax.swing.JButton btmr;
    private javax.swing.JButton btms;
    private javax.swing.JButton btporcentagem;
    private javax.swing.JButton btraiz;
    private javax.swing.JButton btvezes;
    private javax.swing.JButton btvirgula;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPanel painelbotoes;
    private javax.swing.JTextField txtVisor;
    // End of variables declaration//GEN-END:variables
}
